
[webservers]
server1.local ansible_host=192.168.1.251

[dbservers]
server2.local ansible_host=192.168.1.252

[infra:children]
webservers
dbservers


[all:vars]
ansible_ssh_pass = 1234
ansible_become_pass = 1234

# of course it would be security best practices to put this in a vault with a hidden password file but I put this here for convenience!
db_password = "Sicheres_DB_Passwort!!"
